language: node_js
node_js:
  - stable

cache:
  directories:
    - node_modules

before_install:
  - yarn install

before_script:
  - yarn compile

script:
  - yarn test

after_success: yarn coverage
